spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/map?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: thfla0901@
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      # 개발 초기 단계 또는 로컬에서 테스트: create 또는 update
      # 테스트 서버: update 또는 validate
      # 스테이징 및 운영 서버: validate 또는 none
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org:
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE