spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whatToEat?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: hoon@0815!!
    hikari:
      maximum-pool-size: 20

  jpa:
    hibernate:
      # ?? ?? ?? ?? ???? ???: create ?? update
      # ??? ??: update ?? validate
      # ???? ? ?? ??: validate ?? none
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true

    properties:
      hibernate:
        format_sql: true

logging.level:
  org:
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE