spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whatToEat?serverTimezone=UTC&characterEncoding=UTF-8

    username: root
    password: ${MYSQL_PW}
    hikari:
      maximum-pool-size: 50 # 최대 커넥션 수를 50으로 설정
#      connection-timeout: 60000 # 커넥션 획득 대기 시간을 60초로 설정
#      validation-timeout: 3000 # 유효성 검사 시간을 3초로 설정
#      idle-timeout: 600000 # 유휴 상태 커넥션 유지 시간을 10분으로 설정
#      min-idle: 10 # 최소 유휴 커넥션 수를 10으로 설정
#      max-lifetime: 1800000 # 커넥션 최대 생존 시간을 30분으로 설정
  mustache:
    suffix: .html
  profiles:
    include: jwt
  jpa:
    hibernate:
      # 개발 초기 단계 또는 로컬에서 테스트: create 또는 update
      # 테스트 서버: update 또는 validate
      # 스테이징 및 운영 서버: validate 또는 none
      ddl-auto: create
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true

logging.level:
  org:
#    springframework.security: DEBUG
    hibernate:
      SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

tmap:
  api:
    key: ${TMAP_API_KEY}

naver:
  service:
    url: https://0r5887jrbp.apigw.ntruss.com/custom/v1/28830/da1e56e39c8d3213aa260e082ac4da2d93ef75049c8db0cdc6ee629fa56b05f7/general
    secretKey: ${NAVER_SERVICE_KEY}